name: Minha Primeira Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  exemplo:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o cÃ³digo
        uses: actions/checkout@v4

      - name: Mostrar mensagem
        run: echo "Pipeline funcionando ðŸŽ‰"
